Add --show-combinational-progress option
virtualsecureplatform/Iyokan pull request #9
Opened 2021-09-09 05:09 UTC by naoki9911

Show logic execution progress every 1000 gates

![image](https://user-images.githubusercontent.com/33079554/132626276-08850b55-fb5f-4833-a8f5-fdfa00f0c957.png)

2021-09-09 05:23 UTC, ushitora-anqou requested changes

2021-09-09 05:23 UTC, ushitora-anqou commented on src/iyokan.hpp
> +    bool stdoutCSV, skipReset, showCombinationalProgress = false;
```c++
    bool stdoutCSV = false, skipReset = false, showCombinationalProgress = false;
```

2021-09-09 05:23 UTC, ushitora-anqou commented on src/iyokan_cufhe.hpp
> +    void run(const Options& opt)
`run` に `Options` を渡すのではなくて `CUFHENetworkRunner` のコンストラクタに必要な引数だけ渡す形にしてほしい。

2021-09-09 05:23 UTC, ushitora-anqou commented on src/iyokan_cufhe.hpp
> +            if (opt.showCombinationalProgress && nowCount - prevCount > 1000) {
本当は `fprintf` でなくて `spdlog::debug` とかを使ってほしい感じがするが、そうすると更新していくような表示はできないので悩みどころ。

2021-09-09 06:16 UTC, naoki9911 commented on src/iyokan_cufhe.hpp
> +            if (opt.showCombinationalProgress && nowCount - prevCount > 1000) {
そうですね。

2021-09-09 07:10 UTC, ushitora-anqou requested changes

2021-09-09 07:10 UTC, ushitora-anqou commented on src/iyokan_cufhe.hpp
> +        showCombProg_ = showCombProg;
member initializer listを使ってください。 https://en.cppreference.com/w/cpp/language/constructor つまり687行目を
```c++
     : graph_(std::move(graph)), showCombProg_(showCombProg)
```
にしてください。

2021-09-09 07:10 UTC, ushitora-anqou commented on src/iyokan_cufhe.hpp
> +        showCombProg_ = showCombProg;
plain/tfheppも同様にお願いします。

2021-09-09 07:10 UTC, ushitora-anqou commented on src/main.cpp
ここの空行を削除してください。

2021-09-10 02:41 UTC, ushitora-anqou approved these changes

2021-09-10 02:42 UTC, merged